name: Email Test Workflow

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 23f2005020@ds.study.iitm.ac.in
        run: echo "Hello, world!"
